# golangci-lint v2 configuration
# https://golangci-lint.run/usage/configuration/

version: "2"

run:
  timeout: 5m

linters:
  default: standard
  disable:
    - depguard  # Not needed for this project

formatters:
  enable:
    - gofmt
    - goimports
